language: ruby
dist: trusty
sudo: false
group: beta
cache: bundler

branches:
  only: [master]

rvm:
  - 1.9
  - 2.2.6
  - 2.3.3
  - ruby-head
  - 2.4.0

gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile

addons:
  apt:
    packages:
      - haveged

before_install:
  - service haveged start

matrix:
  include:
    - rvm: jruby-1.7.26
      env: JRUBY_OPTS="--dev"
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.1.6.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.1.6.0
      env: JRUBY_OPTS="--dev -J-Djruby.launch.inproc=true -J-Xmx1024M"
      gemfile: gemfiles/rails5.gemfile
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.2.6
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails5.gemfile
