language: ruby

rvm:
  - jruby-19mode
  - 1.9
  - 2.2
  - 2.3
  - ruby-head

gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails5.gemfile

sudo: false

matrix:
  include:
    - rvm: jruby-1.7.24
      env: JRUBY_OPTS="--2.0"
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails42.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails5.gemfile
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails32.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails32.gemfile
    - rvm: 1.9
      gemfile: gemfiles/rails5.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails5.gemfile
