name: Build Release

on:
  push:
    branches:
      - release-*/**
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 # v2
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
    - name: Capture sdk name
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref }}
        regex: 'refs\/heads\/release-(sentry-\w+)\/.*'
    - name: Set sdk-directory path
      run: echo ${{format('sdk-directory={0}', steps.regex-match.outputs.group1)}} >> $GITHUB_ENV
    - name: Build gem source
      working-directory: ${{env.sdk-directory}}
      run: make build
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}
        path: ${{env.sdk-directory}}/*.gem
