name: sentry-sidekiq Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - \d+-\d+
  pull_request:
# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    defaults:
      run:
        working-directory: sentry-sidekiq
    name: Ruby ${{ matrix.ruby_version }} & Sidekiq ${{ matrix.sidekiq_version }}, options - ${{ toJson(matrix.options) }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sidekiq_version: ["5.0", "6.0", "7.0"]
        ruby_version: ["2.7", "3.0", "3.1", "3.2", "3.3", jruby]
        include:
          - { ruby_version: 2.4, sidekiq_version: 5.0 }
          - { ruby_version: 2.5, sidekiq_version: 5.0 }
          - { ruby_version: 2.5, sidekiq_version: 6.0 }
          - { ruby_version: 2.6, sidekiq_version: 5.0 }
          - { ruby_version: 2.6, sidekiq_version: 6.0 }
          - { ruby_version: jruby, sidekiq_version: 5.0 }
          - { ruby_version: jruby, sidekiq_version: 6.0 }
          - { ruby_version: jruby, sidekiq_version: 7.0 }
          - {
              ruby_version: "3.2",
              sidekiq_version: 7.0,
              options:
                {
                  rubyopt: "--enable-frozen-string-literal --debug=frozen-string-literal",
                },
            }
          - {
              ruby_version: "3.2",
              sidekiq_version: 7.0,
              options: { codecov: 1 },
            }
    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          cache-version: 1

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.sidekiq_version == '7.0' && 6 || 5 }}

      - name: Run specs with Sidekiq ${{ matrix.sidekiq_version }}
        env:
          SIDEKIQ_VERSION: ${{ matrix.sidekiq_version }}
          RUBYOPT: ${{ matrix.options.rubyopt }}
        run: |
          bundle install --jobs 4 --retry 3
          make test

      - name: Upload Coverage
        if: ${{ matrix.options.codecov }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
